### ISSUE TITLE
Gathering places have no workers

### ISSUE THREAD

**Issue by Zara84** [lvanhee/COVID-sim#107]
I've noticed some gathering-places (that are not homes or away) have no workers in the "hired-workers" variable. Is that by design? If not there, where should I look for who works where?

**Comment by lgludescher** [comment]
Exactly, I was about to report this issue. For example, in the default-scenario there are 10 non-essential shops and only 5 workers working in non-essential shops. This has an important effect on the economic model, because wages are considered fixed costs and if certain gathering point has no workers it never goes bankrupt.
![image](https://user-images.githubusercontent.com/19166648/80135427-80c6df80-85a0-11ea-80d3-768dbe05ef57.png)
![image](https://user-images.githubusercontent.com/19166648/80135460-8d4b3800-85a0-11ea-8c1a-5a2589064020.png)

**Comment by lgludescher** [comment]
Solved.
