### ISSUE TITLE
Sometimes money disappears from the system

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#40]
Some runs  it disappears, some times it doesn't.

![image](https://user-images.githubusercontent.com/59364209/77861515-c7315480-7215-11ea-9df9-3fbf0f831ec2.png)

**Comment by lgludescher** [comment]
Yeah, total capital should be always the same. I'm investigating this.

**Comment by MelchiorUU** [comment]
When agents die some get removed, but they don’t die in this case.

**Comment by lgludescher** [comment]
I simulated the scenario you presented and noted that people are simply dying. For instance, from initial population = 300, after ~200 ticks total population = 237. So, no bug identified, since the total capital is going out of the system because of people dying. We can discuss what should be done in these cases, but it's not a bug.

**Comment by MelchiorUU** [comment]
In the cases with infections, yes. But this happened in a case without infections. But it doesn’t happen always :/.

**Comment by lgludescher** [comment]
I couldn't reproduce this. The only way to decrease the total amount of capital in the system is by killing people and/or gathering points. If you see this again in scenarios **without infections**, please take a print that includes all parameters and graphs. :)

**Comment by lgludescher** [comment]
No additional evidence was presented. If this happens again take a screenshot including all parameters and reopen the issue.
