### ISSUE TITLE
shop workers stay at home in the weekends

### ISSUE THREAD

**Issue by mijkehurk** [lvanhee/COVID-sim#82]
When it is weekend saturday/sunday morning/afternoon there seem to be no workers at the shops (#workers-working-at-essential-shop = 0)

**Comment by rmellema** [comment]
This is correct. In order to keep the simulation simpler all the agents have the same work schedule, so they work from monday till friday on the morning and afternoon, but not in the weekends. At first this only mattered for shops, but with the increase in different types of workers, this might need to be reevaluated.

**Comment by lvanhee** [comment]
Shop workers should now work on Saturday but no Sundays and people will not attempt do do shopping on Sunday.
