### ISSUE TITLE
x-axis label of charts (days instead of time)

### ISSUE THREAD

**Issue by lorigf** [lvanhee/COVID-sim#85]
The charts currently show "time" on the x-axis where 4 timesteps are 1 day. It would be easier to read these charts if the x-axis would display days instead. 

(originally mentioned during the zoom meeting by Tomas)

**Comment by Tomas-Sjostrom** [comment]
Ty Fabian, some more motivation

Day may be a more intuitive timescale for the outputgraphs. The user is probably more interested in the number of days that the simulation have run and would then not need to divide the time by 4(1/timesstep) to get the days. 

There is nothing wrong with having a different timescale in between the UI and the simulation. For instance in realtime simulation where the simulation may run at 1/60 of a second and the outputgraphs are most easily understood when they are in seconds and not 60*seconds,

**Comment by rmellema** [comment]
I'm not sure if setting this up on the netlogo side is a good idea, since for the calibration of the model it is good to see what happens at every tick, not just every day. Then we would need separate plots to show to other people and ones to use in the design of the model.
This is of course not the case for every plot, so it should be possible to do this for the population status, but I'm not sure if having plots with different time scales is not going to lead to more confusion.

**Comment by lvanhee** [comment]
Let's leave it out in Netlogo and save it for the R code; and make sure that "ticks" or "days" is mentionned.
